apiVersion: v1
kind: Secret
metadata:
  name: nexuscloud-secrets
  namespace: nexuscloud
type: Opaque
stringData:
  JWT_SECRET: "nexuscloud-super-secret-key-k8s"
  DB_PASSWORD: "nexuscloud_password"
  DB_USER: "nexuscloud"
  DB_NAME: "nexuscloud_db"